### ISSUE TITLE
Enhance installation instructions

### ISSUE THREAD

**Issue by yannou38** [jeremy-rifkin/cpptrace#66]
Hello,

I've been having troubles using your project in mine (on windows, using MSVC for now, but will also use mingw later). I managed to make it work (and it work fine, thanks !), but just wanted to make some return on it

I noticed the target name in the readme was cpptrace, but it should be cpptrace::cpptrace or cpptrace_lib.

Also, i'm not sure this project is compatible with mingw, i've been having a compilation error on the libdwarf dependency.

**Comment by jeremy-rifkin** [comment]
Hi @yannou38, thank you for your interest in the library!

Thanks for noticing that the readme reads `cpptrace` instead of `cpptrace::cpptrace`, I'll fix that now.

What issues have you ran into with using the library on windows with your project and what issues are you running into with mingw? The project does work with mingw and libdwarf will be built as part of cpptrace.

**Comment by yannou38** [comment]
Hello ! Thanks for replying.

I can't log a trace right now, but for building on mingw it was a problem in libdwarf, who couldn't find O_READONLY symbol (or something close to it, i'm speaking about the flags for file opening). I think it's a missing header.
My installation of mingw come from winlibs, and is up to date.

**Comment by jeremy-rifkin** [comment]
Thanks for the reply, I'm wondering if winlibs is missing a header (fnctl.h) or a definition in a header. It would be best to open an issue upstream at https://github.com/davea42/libdwarf-code.

**Comment by jeremy-rifkin** [comment]
I've setup a fresh vm with the most recent installation of winlibs and I'm unable to reproduce a build failure.

**Comment by yannou38** [comment]
[here is a log file from our CI (CI setup is a bit special however)](https://github.com/jeremy-rifkin/cpptrace/files/13672901/10_Build.txt).

and here is a part of the cmakefile focusing on external packages, in case you need it
```
#Dependencies are handled using scripts from CPM project
# https://github.com/cpm-cmake/CPM.cmake
set(CPM_DOWNLOAD_VERSION 0.35.1)
set(CPM_SOURCE_CACHE "C:/Cache/CPM" CACHE PATH "path to CPM cache  folder")
include("${CMAKE_SOURCE_DIR}/GitTemplate/cmake/downloadCPM.cmake")

CPMAddPackage("gh:nlohmann/json@3.10.5") #Creates target nlohmann_json (ALIAS of nlohmann_json::nlohmann_json)
CPMAddPackage("gh:fmtlib/fmt#9.1.0") # Creates target fmt
CPMAddPackage(GITHUB_REPOSITORY "gabime/spdlog" VERSION 1.11.0 OPTIONS "SPDLOG_FMT_EXTERNAL 1" ) #Creates target spdlog
CPMAddPackage("gh:jarro2783/cxxopts@3.1.1") #Creates target cxxopts
CPMAddPackage("gh:jeremy-rifkin/cpptrace#v0.3.1") #Creates target cpptrace::cpptrace
```

I hope that helps you. I can't exclude it's something to do with us, or another package, but the build fail both on CI and my workstation (both are W10).

**Comment by jeremy-rifkin** [comment]
Thank you so much for the error log, that's perfect. It confirms it is in dwarf_generic_init.c :)

**Comment by jeremy-rifkin** [comment]
Other files in libdwarf using O_RDONLY have a snippet like
```cpp
#ifndef O_RDONLY
#define O_RDONLY 0
#endif
```but dwarf_generic_init.c does not

**Comment by vtorri** [comment]
it is not a good solution. the problem is not on the libdwarf side. It is in the mingw installation. I use msys(2) + mingw64 since 2008 and the fcntl.h header file has always been installed. I'm compiling libdwarf for several years (and helped its author) without any problem

patching a project for a bad  reason (installation broken) should not be done. First try to understand why fcntl.h is not present.

my recommendation is : use MSYS2 and install mingw with it.

btw, i've just downloaded winlibs and fcntl.h is there (in mingw64\x86_64-w64-mingw32\include\). So the problem is on your side, not on libdwarf one

**Comment by jeremy-rifkin** [comment]
Hi @vtorri, fnctl is present but presumably NO_OLDNAMES is being defined.

**Comment by jeremy-rifkin** [comment]
0.4 has been released
