### ISSUE TITLE
add object address to stacktrace_frame

### ISSUE THREAD

**Issue by eyalgolan1337** [jeremy-rifkin/cpptrace#97]
When generating a stack trace using `stacktrace::current()`, the resulting stackframe object contains a vector of `stacktrace_frame`s.
the stacktrace_frame struct contains these fields:
```
frame_ptr address;
nullable<std::uint32_t> line;
nullable<std::uint32_t> column;
std::string filename;
std::string symbol;
bool is_inline;
```
What I'm missing is the relative address inside the object (like the `object_address` member in the `object_frame` struct).
This is crucial because  the addresses returned by `cpptrace` are relative for the process executable (0x2000 bytes from the start of the file, for example) but absolute for every other `.so` in memory (0x7ffff54000 from start of process memory).

In scenarios when the binary is stripped and only the address and the object path can be retrieved the relative address inside the object is the only way to gain any insight as to where the call in the `.so` came from

**Comment by jeremy-rifkin** [comment]
Hi, thanks for opening this. I'm going to give this some thought - Initially I hadn't included the object address because it's usually not needed by the user however it probably wouldn't hurt to include it.

At the moment the solution will be to do this, and get the information you need either by index or maybe with `std::ranges::views::zip` (or similar):
```cpp
auto object_trace = cpptrace::object_trace::current();
auto trace = object_trace.resolve();
```

This isn't the most ergonomic, though.

**Comment by jeremy-rifkin** [comment]
I had a realization that the object address alone is probably not all that useful without an object path along with it. At that point `stacktrace_frame` may as well extend `object_frame`, but I'm weary of this because it's a lot of overhead that won't be relevant in most use-cases. I think it will be better to add a `object_frame get_object_info() const;` to the `stacktrace_frame` that will get this extra info as needed.
